spring:
    kafka:  
        producer:
            bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
            key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            ssl:
              trust-store-location: file:/usr/local/kafka/config/ssl-certs/client.truststore.jks
              trust-store-password: 12345678
              key-store-location: file:/usr/local/kafka/config/ssl-certs/client.keystore.jks
              key-store-password: 12345678
            properties:
              acks: all
              retries: 10
              retry.backoff.ms: 1000
              security:
                protocol: SSL
              ssl.endpoint.identification.algorithm:
        admin:
          properties:
            bootstrap.servers: localhost:9095,localhost:9096,localhost:9097

server:
  port: 8090